### ISSUE TITLE
[Blog Post] Post displays only 1 author name but more authors added on Ghost

### ISSUE THREAD

**Issue by Zheng-Shilin** [forbole/official-website#197]
I found out that the post on our website can only display the first author, but actually the post in Ghost has multiple authors. For example: https://www.forbole.com/blog/big-dipper-2020-nian-du-hui-gu/, both Caroline and I are the authors of this post in Ghost, but it only shows my name here. Could you fix that? I think in the future, we will have posts that are drafted by multiple people too, or if we have translation posts which might need to display both the author and translator's name.

**Comment by rachelhox** [comment]
There's another post in English written by Carolie. Do you mean this one?
https://www.forbole.com/blog/big-dipper-2020-yearly-review
![image](https://user-images.githubusercontent.com/53459742/106771629-23f16d00-667a-11eb-9665-b0360e3380c3.png)

**Comment by Zheng-Shilin** [comment]
Caroline and I are both the authors of the Big Dipper Review Chinese and English version. I meant, she should be also showing on the Chinese post, and my name should be displayed in this English one as well.

**Comment by rachelhox** [comment]
@Zheng-Shilin Ok gotcha! I'd discuss with @Rooty2020 about some layouts on blog/mooncake/home sessions now that some of the info needs to be updated!
