### ISSUE TITLE
Delegation APIs

### ISSUE THREAD

**Issue by rachelhox** [forbole/official-website#213]
## Feature description 

1) Kava 
2) Likecoin 
3) Starname/IOV 
4) Band 
5) Akash 
6) E-money 
7) Iris

**Comment by kwunyeung** [comment]
@rachelhox I have linked back https://ws.cosmoshub.forbole.com and http://lcd.cosmoshub.bigdipper.live to the latest mainnet. Please help to check the data is linked back up.

**Comment by rachelhox** [comment]
> @rachelhox I have linked back https://ws.cosmoshub.forbole.com and http://lcd.cosmoshub.bigdipper.live to the latest mainnet. Please help to check the data is linked back up.

Kava
Likecoin
Starname/IOV
Band
Akash
E-money
Iris

these networks' apis are currently down at the moment

**Comment by rachelhox** [comment]
Flow and Solana
