### ISSUE TITLE
Next.js dynamic routing fix

### ISSUE THREAD

**Issue by rachelhox** [forbole/official-website#214]
## Feature description 

Found the correct way of doing dynamic routing and redirecting with Next.js `Link` component.

File structure with dynamic routing under `/pages/` directory:
https://github.com/vercel/vercel/issues/3294#issuecomment-739250378

Referencing dynamic routes or variables with `Link` componenet:
https://github.com/vercel/vercel/issues/3294#issuecomment-666575214
https://github.com/mattcarlotta/nextjs-basic-data-fetch/blob/master/pages/index.js

Pushing the dynamic link with new query (e.g., page numbers...)
https://github.com/vercel/vercel/issues/3294#issuecomment-592303143

**Comment by kwunyeung** [comment]
Nice references!
