### ISSUE TITLE
Update API endpoints

### ISSUE THREAD

**Issue by kwunyeung** [forbole/official-website#218]
Some API endpoints are updated on some networks. Also the hook is getting all data before return which makes the wheel not working if any of the endpoint is dead.

![image](https://user-images.githubusercontent.com/932636/109765087-549fd480-7c2f-11eb-99a1-4c597c08556e.png)

**Comment by kwunyeung** [comment]
This also affect the rewards calculator.

**Comment by rachelhox** [comment]
Flow and Solana endpoints still needed

**Comment by kwunyeung** [comment]
@dadamu can you provide @rachelhox the correct endpoint and function for querying our stake on Solana?

**Comment by dadamu** [comment]
There are testnet and mainnet endpoints.
Mainnet: https://api.mainnet-beta.solana.com/
Testnet: https://testnet.solana.com/ 

The method to get all vote status like activatedStake is getVoteAccounts.
Doc: https://docs.solana.com/developing/clients/jsonrpc-api#getvoteaccounts

**Comment by kwunyeung** [comment]
Not calling all networks from the endpoints directly. Closing now.
