### ISSUE TITLE
Author page is not accessible directly

### ISSUE THREAD

**Issue by kwunyeung** [forbole/official-website#246]
https://www.forbole.com/author/crystal can't be access if you visit it directly from web browser but it's accessible if you click the link in a web page. For example, it works when a user visit the author page from this blog post https://www.forbole.com/blog/how-does-ibc-work

**Comment by rachelhox** [comment]
https://stackoverflow.com/questions/62341093/prefetching-not-working-on-dynamic-routes-next-js

**Comment by rachelhox** [comment]
https://stackoverflow.com/questions/48736902/how-do-you-get-query-params-from-the-url-in-getinitialprops

Handling get request with Nextjs server
