### ISSUE TITLE
Network not updated when token buttons are clicked

### ISSUE THREAD

**Issue by kwunyeung** [forbole/official-website#271]
In the reward calculator, the corresponding is highlighted when the drop down item is selected. However, when I click the token buttons, the network is not switched to the corresponding one.

![image](https://user-images.githubusercontent.com/932636/116770319-81c50380-aa75-11eb-881d-360e417a78de.png)

**Comment by rachelhox** [comment]
https://stackoverflow.com/questions/60798714/how-to-change-react-select-options-styles-when-select
