### ISSUE TITLE
Forbole website homepage project logos and links

### ISSUE THREAD

**Issue by Zheng-Shilin** [forbole/official-website#275]
- [x] - Agoric:  take down
- [x] - Akash: good
- [x] - Band: good
- [x] - BitSong: link to https://play.bitsong.io/ 
- [ ] - Celo: change stake now wording to “explore” link: https://celo.bigdipper.live/
- [ ] - CosmWasm - add logo and explorer link “visit” https://www.cosmwasm.com/ 
- [x] - Cosmos Hub: good
- [x] - Crypto.org: add logo; stake now link to https://crypto-org.bigdipper.live/validator/crocncl15xphw2m025acwnjd2ucq9t5ku4ggaqyecekzqa 
- [x] - E-money: stake now link change to https://wallet.e-money.com/earn/emoneyvaloper1293pqwtzu67zp8txuya4yts03ccw5kgf98hz9y
- [x] - Fetch.AI: stake now link change to https://explore.fetch.ai/validator/fetchvaloper14kn0kk33szpwus9nh8n87fjel8djx0y0dzxfx3
- [x] - Flow: change stake now link to https://port.onflow.org/ 
- [x] - Injective: change “stake now” link to https://staking.injective.network/connect 
- [x] - IOV: change name to “Starname”, stake now link to  https://big-dipper.iov-mainnet-2.iov.one/validator/starvaloper1jkv2qkpq6cfplx6put7f00wzuyds57fnmtgde0 
- [x] - Iris hub: good
- [x] - Kava: stake now link not working
- [x] - Kusama: change stake now link to https://polkadot.js.org/apps/#/accounts 
- [x] - LikeCoin: good
- [x] - Oasis Lab: take down 
- [x] - Oasis Protocol: change stake now link to https://anthem.chorus.one/networks 
- [x] - Persistence: take down
- [x] - Polkadot: change stake now link to https://polkadot.js.org/apps/#/accounts 
- [x] - Regen network: change stake now link to https://wallet.keplr.app/#/regen/stake?modal=detail&validator=regenvaloper14kn0kk33szpwus9nh8n87fjel8djx0y0c7xhe5 
- [x] - Sentinel: change to the correct logo; change stake now link to https://explorer.sentinel.co/validator/sentvaloper14kn0kk33szpwus9nh8n87fjel8djx0y0l9e6u8  
- [x] - Sharering: take down sharering
- [x] - Solana: stake now link to https://solflare.com/ 
- [x] - Straightedge: take down (confirm with @kwunyeung)
- [x] - Terra Money: change stake now link to https://station.terra.money/validator/terravaloper1jkqr2vfg4krfd4zwmsf7elfj07cjuzss30ux8g 
- [x] - V Systems: add logo; stake now link to https://wallet.v.systems/

**Comment by rachelhox** [comment]
@Zheng-Shilin so are we taking down Straighedge?

**Comment by rachelhox** [comment]
Kava link seems to be working on staging now
https://kava.bigdipper.live/validators/kavavaloper14kn0kk33szpwus9nh8n87fjel8djx0y02c7me3/delegate

**Comment by Zheng-Shilin** [comment]
@rachelhox The buttons under Celo and CosmWasm are not for staking, should be "explore" and "visit". Could you change that? Also, probably better to move Starname next to Solana according to the alphabetical order. Should I reopen the issue?

**Comment by rachelhox** [comment]
ok! I'm hiding Celo (since Celo is shown on Products Page under Big Dipper `Supported Networks`), and hiding CosmWasm on Stake Now while showing this as `Coming Soon` on Home Page.

**Comment by Zheng-Shilin** [comment]
@rachelhox looks like Starname has been changed to IOV again?

**Comment by rachelhox** [comment]
> @rachelhox looks like Starname has been changed to IOV again?

Yep! It would be changed to `Starname` on next release!
