### ISSUE TITLE
Styles are breaking with latest FomaticUI

### ISSUE THREAD

**Issue by kwunyeung** [forbole/official-website#300]
I have tried upgrading all packages including `FomaticUI`. After rebuilding styles, all font sizes and margins have been changed.

**Comment by rachelhox** [comment]
Should we still update the `FormanticUI` packages then change the styles accordingly? 
@kwunyeung

**Comment by kwunyeung** [comment]
@rachelhox yes I think so. I was doing `yarn upgrade` and the theme is not the same as before. Some packages are old. I eventually only upgraded `next`, `react` and `react-dom`.
