### ISSUE TITLE
Blog tag page keeps loading

### ISSUE THREAD

**Issue by kwunyeung** [forbole/official-website#301]
It's having the same loading behaviour as the blog page before. I thinks it's not fixing on tag page. That makes the careers posts can never be found.

https://www.forbole.com/tag/careers

**Comment by rachelhox** [comment]
The tag page for careers was working locally as the getPost func was not the same for Blog Page and Tag Page. I'll look into and fix it asap
@kwunyeung

**Comment by rachelhox** [comment]
Seems to be a cache from cloudflare
