### ISSUE TITLE
Add Axelar, Chihuahua, Lum and SSV

### ISSUE THREAD

**Issue by Rooty2020** [forbole/official-website#359]
Chihuahua stake now: https://chihuahua.omniflix.co/
Lum Network stake now: https://wallet.lum.network/welcome
Axelar Network: https://axelar.network/ (put coming soon...)
SSV: https://ssv.network/ 
(Shilin is writing a post to introduce SSV so maybe wait for the link for my post). It is testnet, so maybe we can say sth like "try out now"...

**Comment by Rooty2020** [comment]
![chihuahua.png](https://images.zenhubusercontent.com/6111e85453613f2c8109c600/aafcf17c-4e5e-419f-a7b7-55155dbe4b70)
![Axelar Network.png](https://images.zenhubusercontent.com/6111e85453613f2c8109c600/69213ba8-7da5-4e79-b122-d15ffe07acb8)

![Lum.png](https://images.zenhubusercontent.com/6111e85453613f2c8109c600/311bac3c-9a12-45a1-bff1-e7a4f88dedcd)

![SSV.png](https://images.zenhubusercontent.com/6111e85453613f2c8109c600/573b0d85-7f2a-457c-9b80-4b6c8c0ce5ec)

**Comment by kanniec826** [comment]
@rachelhox Please help on it after update the DSM airdrop website
