### ISSUE TITLE
Change Cosmwasm logo to Tgrade

### ISSUE THREAD

**Issue by Rooty2020** [forbole/official-website#361]
Please take down the Cosmwasm Logo on our website and replace it with Tgrade (we are joining as a validator): https://tgrade.finance/

**Comment by Rooty2020** [comment]
Logo:
https://drive.google.com/file/d/1ujPD_i6T5PCANn9PdS-rKDLH9PK8_g9S/view?usp=sharing

**Comment by Rooty2020** [comment]
![Tgrade.png](https://images.zenhubusercontent.com/6111e85453613f2c8109c600/7a160f87-96a7-4002-ae2b-1327fee676ae)

**Comment by kanniec826** [comment]
@rachelhox Please help on it after update the DSM airdrop website
