### ISSUE TITLE
Add Comdex logo

### ISSUE THREAD

**Issue by Zheng-Shilin** [forbole/official-website#369]
We are validating on Comdex. Please add its logo to our website. 
Stake now link please use the keplr one.

**Comment by Rooty2020** [comment]
https://drive.google.com/file/d/12zkUIsGNOE7S0TTBjbbYA4uq_b1alhKK/view?usp=sharing
![comdex.png](https://images.zenhubusercontent.com/6111e85453613f2c8109c600/7fa50332-31d8-41ab-a6bb-02fbef038bcc)

**Comment by kanniec826** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Issue-61d56716a7505500117ec7f1/issues/forbole/official-website/369?planning-poker) with ZenHub @rachelhox
