### ISSUE TITLE
Wormhole has new logo

### ISSUE THREAD

**Issue by Zheng-Shilin** [forbole/official-website#371]
Wormhole project has a new logo. Please let me know if you can't find it on the website. I will ask the wormhole team to send logo pics directly. @Rooty2020

**Comment by Rooty2020** [comment]
https://drive.google.com/file/d/1nNct1U0lG_k24obtP6YgI7ey2gx4Qf8R/view?usp=sharing

![Wormhole.png](https://images.zenhubusercontent.com/6111e85453613f2c8109c600/b9483df1-c470-49fe-b075-e5a3ba93ced0)

**Comment by kanniec826** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Issue-61d56716a7505500117ec7f1/issues/forbole/official-website/371?planning-poker) with ZenHub @rachelhox
