### ISSUE TITLE
Add Gravity Bridge and Nomic logos

### ISSUE THREAD

**Issue by Zheng-Shilin** [forbole/official-website#374]
We are on Gravity Bridge and Nomic network, please add their logos. Staking links can use the one on Keplr?

**Comment by rachelhox** [comment]
@Rooty2020 Please send the logos for Gravity Bridge and Nomic network! TYSM:)

**Comment by rachelhox** [comment]
@Zheng-Shilin Please send me the staking link for their Keplr!
