### ISSUE TITLE
Application Form

### ISSUE THREAD

**Issue by Rooty2020** [forbole/official-website#378]
https://www.figma.com/file/RtH7MsYw5X0iBdiLTM7eNS/Desmos-Grant-Programme-1.0?node-id=0%3A1

**Comment by kanniec826** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Issue-61d56716a7505500117ec7f1/issues/forbole/official-website/378?planning-poker) with ZenHub @rachelhox

**Comment by kanniec826** [comment]
@rachelhox Any update on this?

**Comment by rachelhox** [comment]
@kanniec826 @Rooty2020 please open this issue on desmos-website!

**Comment by kanniec826** [comment]
Refer to #85
