### ISSUE TITLE
Got 404 when I click a direct link to a specific blog

### ISSUE THREAD

**Issue by kwunyeung** [forbole/official-website#389]
This is what happened when I clicked the link directly from Telegram. I think this is a front end issue. Would it become 404 if the website front end can't get response from the backend sometime?

![6193844f1dfed4b121a3a3d312e6662ee904cc4635aa10b30ba19e29681ffe5b](https://user-images.githubusercontent.com/932636/162355492-3e298bfc-2262-4a75-a4e8-e03783ebda8c.jpg)

**Comment by rachelhox** [comment]
@kwunyeung this has not happened before, is the blog post recently published? Let me look into this issue from GhostCMS side

**Comment by kwunyeung** [comment]
@rachelhox yes this is from the latest blog post. I clicked it directly from the link on TG mobile and it brings me 404 but it works when I visit it on desktop. Jade and Caroline both got 404 when they visited on desktop computers.
